{
 "title": "Refiner Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Block Result Uploads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "refiner_events_brp_upload_success_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "refiner_events_refiner_pipeline_success_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Failure",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "refiner_events_refiner_pipeline_failure_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refiner Events Success Count",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "refiner_events_refiner_pipeline_success_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "refiner_events_ipfs_fetch_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "refiner_events_brp_upload_success_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refiner Pipeline Event Durations",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 21, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "refiner_events_refiner_pipeline_success_duration",
     "legendFormat": "__auto"
    },
    {
     "expr": "refiner_events_brp_proof_duration",
     "legendFormat": "__auto"
    },
    {
     "expr": "refiner_events_ipfs_fetch_duration",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}